service: plugue-back

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  profile: plugue

# you can define service wide environment variables here
#  environment:
#    variable1: value1


functions:
  CreateIdea:
    handler: src/functions/idea/create/handler.main
    events:
      - http:
          path: /idea
          method: post
          cors: true
  UpdateIdea:
    handler: src/functions/idea/update/handler.main
    events:
      - httpApi:
          path: /idea/{IdeaId}
          method: put
  DeleteIdea:
    handler: src/functions/idea/delete/handler.main
    events:
      - httpApi:
          path: /idea/{ideaId}
          method: delete
  GetIdea:
    handler: src/functions/idea/get/handler.main
    events:
      - httpApi:
          path: /idea/{ideaId}
          method: get
  CreateUser:
    handler: src/functions/user/create/handler.main
    events:
      - http:
          path: /user
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - Accept
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        # Generate a name based on the stage
        UserPoolName: plugue-user-pool
        # Set email as an alias
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        # Generate an app client name based on the stage
        ClientName: plugue-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false

#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
