service: plugue-back

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  profile: plugue

# you can define service wide environment variables here
#  environment:
#    variable1: value1


functions:
  CreateIdea:
    handler: src/functions/idea/create/handler.main
    events:
      - httpApi:
          path: idea
          method: post
  UpdateIdea:
    handler: src/functions/idea/update/handler.main
    events:
      - httpApi:
          path: idea/{IdeaId}
          method: put
  DeleteIdea:
    handler: src/functions/idea/delete/handler.main
    events:
      - httpApi:
          path: /idea/{ideaId}
          method: delete
  GetIdea:
      handler: src/functions/idea/get/handler.main
      events:
        - httpApi:
            path: /idea/{ideaId}
            method: get
  ListIdeas:
      handler: src/functions/idea/list/handler.main
      events:
        - httpApi:
            path: /idea/
            method: get
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
